"use client";
import { useMemo, useState, useTransition } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarClock, Eye, Paperclip, Save, Send } from "lucide-react";
import { saveDraftAction } from "@/app/actions/communications";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { inputClass } from "@/components/ui/field";
import { PageHeader } from "@/components/ui/page-header";
import type { CommunicationAccount, CommunicationTemplate } from "@/lib/types";

export function CommunicationCompose({accounts,templates}:{accounts:CommunicationAccount[];templates:CommunicationTemplate[]}){
 const [to,setTo]=useState(""),[cc,setCc]=useState(""),[bcc,setBcc]=useState(""),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[mobile,setMobile]=useState(false),[message,setMessage]=useState(""); const [pending,start]=useTransition();
 const sender=useMemo(()=>accounts.find(x=>x.is_default)||accounts[0],[accounts]);
 function template(id:string){const t=templates.find(x=>x.id===id);if(t){setSubject(t.subject||"");setBody(t.body);}}
 return <div className="space-y-5"><PageHeader eyebrow="Communication Center" title="Compose Email" description="Prepare a provider-neutral email. Sending and scheduling remain disabled until Gmail integration."><Link href="/communication-center" className="inline-flex items-center gap-2 text-sm font-bold text-navy-700"><ArrowLeft size={16}/>Back</Link></PageHeader>
 {message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}
 <div className="grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(360px,.85fr)]"><Card><form action={f=>start(async()=>{await saveDraftAction(f);setMessage("Draft saved successfully.")})} className="space-y-4"><input type="hidden" name="channel" value="EMAIL"/><label className="block text-sm font-bold text-slate-700">From<input readOnly className={`${inputClass} mt-1 bg-slate-50`} value={sender?.email_address||"projects@adhunikswitchgears.com"}/></label><div className="grid gap-3 md:grid-cols-2"><Field label="To"><input name="to_address" className={inputClass} value={to} onChange={e=>setTo(e.target.value)} placeholder="recipient@example.com"/></Field><Field label="Template"><select className={inputClass} defaultValue="" onChange={e=>template(e.target.value)}><option value="">No template</option>{templates.map(x=><option key={x.id} value={x.id}>{x.template_name}</option>)}</select></Field><Field label="CC"><input name="cc" className={inputClass} value={cc} onChange={e=>setCc(e.target.value)} placeholder="Comma-separated"/></Field><Field label="BCC"><input name="bcc" className={inputClass} value={bcc} onChange={e=>setBcc(e.target.value)} placeholder="Comma-separated"/></Field></div><Field label="Subject"><input name="subject" className={inputClass} value={subject} onChange={e=>setSubject(e.target.value)}/></Field><Field label="Rich text body"><div className="flex gap-1 rounded-t-lg border border-b-0 border-border bg-slate-50 p-2 text-xs font-bold text-slate-500"><span className="rounded bg-white px-2 py-1">Bold</span><span className="rounded bg-white px-2 py-1">Italic</span><span className="rounded bg-white px-2 py-1">List</span><span className="rounded bg-white px-2 py-1">Link</span></div><textarea name="body" required className={`${inputClass} min-h-64 rounded-t-none`} value={body} onChange={e=>setBody(e.target.value)} placeholder="Write your message…"/></Field><div className="rounded-xl border border-dashed border-slate-300 p-4"><div className="flex items-center gap-2 font-bold text-slate-700"><Paperclip size={16}/>Attachments</div><p className="mt-1 text-xs text-slate-500">Choose files from the Communication Attachment Library after storage integration.</p></div><Field label="Signature"><select className={inputClass}><option>Default company signature</option><option>No signature</option></select></Field><div className="flex flex-wrap gap-2"><button disabled={pending} className="primary"><Save size={16}/>Save Draft</button><button type="button" className="secondary"><Eye size={16}/>Preview</button><button type="button" disabled className="secondary opacity-50"><Send size={16}/>Send</button><button type="button" disabled className="secondary opacity-50"><CalendarClock size={16}/>Schedule</button></div></form></Card>
 <Card className="self-start xl:sticky xl:top-24"><div className="flex items-center justify-between"><div><h2 className="font-bold text-navy-900">Live email preview</h2><p className="text-xs text-slate-500">Provider-neutral rendering</p></div><div className="flex rounded-lg bg-slate-100 p-1"><button onClick={()=>setMobile(false)} className={`rounded px-2 py-1 text-xs font-bold ${!mobile?"bg-white":""}`}>Desktop</button><button onClick={()=>setMobile(true)} className={`rounded px-2 py-1 text-xs font-bold ${mobile?"bg-white":""}`}>Mobile</button></div></div><div className={`mx-auto mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm ${mobile?"max-w-[320px]":"w-full"}`}><div className="border-b bg-slate-50 p-4"><p className="font-bold text-slate-900">{subject||"Email subject"}</p><p className="mt-1 text-xs text-slate-500">From: {sender?.email_address||"projects@adhunikswitchgears.com"}</p><p className="text-xs text-slate-500">To: {to||"recipient@example.com"}</p></div><div className="min-h-72 whitespace-pre-wrap p-5 text-sm leading-6 text-slate-700">{body||"Your email content will appear here."}<div className="mt-8 border-t pt-4 text-xs text-slate-500">Adhunik Switchgears Pvt. Ltd.<br/>Default company signature</div></div></div></Card></div><style jsx global>{`.primary,.secondary{display:inline-flex;height:2.5rem;align-items:center;gap:.5rem;border-radius:.5rem;padding:0 1rem;font-size:.875rem;font-weight:700}.primary{background:#102c56;color:#fff}.secondary{border:1px solid #e2e8f0;background:#fff;color:#334155}`}</style></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-bold text-slate-700">{label}<div className="mt-1">{children}</div></label>}
